# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a4d1c6d49d13a159a1124f7152cafc78983391e5a7219c8803c39bb1e1c9cf090c21150ea6b9152fedcae5292d134e5f9cb09e0241d0d9271cf0959f0020aa4

test:
  secret_key_base: 78a164fd68ba60bf49b8fd99d3dce99f0ea1d8e6c2e2d6b9d938b3b7a2221578951fd6cbffb8b522dad174e76f0bb86d47a2b90e75171cb0d972627ebe450820

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
